### ISSUE TITLE
Is there a way to display placeholder data?

### ISSUE THREAD

**Issue by frederikhors** [ConsoleTVs/sswr#14]
I would like to have something like https://sveltequery.vercel.app/guides/placeholder-query-data.

This is useful when you have for example list/detail navigation.

Example: list of users > click on one of them > load from cache (using the list key) > show data > fetch in background for the first time the user data (with a `/user/1`) key.

What do you think?

**Comment by frederikhors** [comment]
I think swr has the same called `initialData`: https://swr.vercel.app/docs/with-nextjs, right?

**Comment by frederikhors** [comment]
I'll try it in a few moments...

**Comment by ConsoleTVs** [comment]
initialData is already supported. I will explore if I am really interested in this but I qould rather like to use the data and error return values to determine if you should show some preview data

**Comment by frederikhors** [comment]
It works as expected. Thanks.
