### ISSUE TITLE
Cannot use `() => string` as key?

### ISSUE THREAD

**Issue by frederikhors** [ConsoleTVs/sswr#16]
Using this line:

```ts
$: ({ data, error } = useSWR(() => `${playerList}`, {...
```

Typescript throws with:

`Argument of type '() => string' is not assignable to parameter of type 'string'.ts(2345)`.

Am I wrong?

**Comment by ConsoleTVs** [comment]
Hum.... https://github.com/ConsoleTVs/sswr/blob/master/src/index.ts#L14

The problem is here https://github.com/ConsoleTVs/sswr/blob/master/src/index.ts#L69

The default instance is not correct... I am going to fix this asap.

**Comment by ConsoleTVs** [comment]
Try the version 1.3.0

**Comment by frederikhors** [comment]
It works. Thanks!

Isn't the code on Github?

**Comment by ConsoleTVs** [comment]
Gonna upload, sorry
