### ISSUE TITLE
Can't get examples to work on Svelte REPL, am I doing something wrong?

### ISSUE THREAD

**Issue by JoshuaJarman** [ConsoleTVs/sswr#2]
**First Example:** https://svelte.dev/repl/6215113361fc45c885566214d2369d1b?version=3.32.3
**Second Example:** https://svelte.dev/repl/d2b8acea29a74439b8f986683b41571b?version=3.32.3

Cut and paste them from the project README.md

Am I doing something wrong?  Thanks!

**Comment by ConsoleTVs** [comment]
Hello, thanks for your report, indeed there was something not working as intended. I've updated all the examples. Please make sure to try again!
