### ISSUE TITLE
Expose a method to get the cache?

### ISSUE THREAD

**Issue by frederikhors** [ConsoleTVs/sswr#20]
In the classic example of `list/detail` if I click on the single detail element I wanna check the cache (under list key) to get data for `initialData` but now there is no way to get cache right?

Should we expose methods for get the cache?

**Comment by frederikhors** [comment]
I would like a method like: `getKeyStartsWith(key: string)` to find for example keys like: `/players?page=1`.

And then I can search values for the `playerId` I need in detail page.

What do you think?

**Comment by ConsoleTVs** [comment]
You've got:

https://github.com/ConsoleTVs/sswr/blob/master/src/index.ts#L105

and 

https://github.com/ConsoleTVs/sswr/blob/master/src/index.ts#L115

**Comment by frederikhors** [comment]
Can we close this?

**Comment by frederikhors** [comment]
~Can we close this?~

I think nope. Wait a moment. I'm trying to use it.

**Comment by frederikhors** [comment]
It works. But.

As I said I'm using it for a "classic" list/detail and here what happens:

1. I'm on the `/players` list page
1. I move on the `/players/1` detail page
1. On detail page I use `get(/players)` to populate my `initialData` to speed up UX
1. **BUT** during this navigation from `/players` to `/players/1` the key `/players` is refetched in background hence the `get(/players)` does not return data, only a Promise, useless in this case

But if I need a `Promise` I can use `getOrWait()` instead.

So I think we should not "change" the cache during refetching because we need to `get()` something even if is stale.

What do you think?

**Comment by frederikhors** [comment]
I think we need a method like `getStartingWith(key: string)`.

**Comment by ConsoleTVs** [comment]
Why not just use the mutate to populate other keys or just use useSWR with revalidation set to false? There is a bunch of options you can pass to it!

**Comment by frederikhors** [comment]
> Why not just use the mutate to populate other keys

I cannot, because I'm checking for data already in cache during new fetch...

> or just use useSWR with revalidation set to false

The players list is refetching because I'm using a variable, and it can depends on other usecases.

Cannot be this the solution.

**Comment by benbender** [comment]
What you are trying to achieve is probably not possible.

1. You are fetching the endpoint for /players and retrieve one(!) object (most likely parsed from a json-string)
2. You are navigating to /players/1 and want the cache to know which part of the data in the cache belongs to player with id 1. Problem is that this information isn't retrieved by the cache.

To achieve such behaviour you could either:
a) parse your one object on the first fetch and populate the cache with individual objects
b) use graphql which has such features because of fragments and strong typing on both ends.

But there is no way to get this for free. You have to type and/or parse your data at some point.

**Comment by frederikhors** [comment]
It's possible.

I'm getting the `players` object which is like this:

```ts
{ players: [{id: "1", name: "Name"}, ...and others] }
```

and with a `.find()` I can find my `player/1`.

**Comment by frederikhors** [comment]
It's doable right now with svelte-query.

**Comment by frederikhors** [comment]
> Just find the player with id = 1

This is what I'm asking you!

If I use `get()` and the query is re-fetching I cannot find players (already fetched before) because I get a promise!

**Comment by ConsoleTVs** [comment]
You have to change step 4 from your list.

- I'm on the /players list page
- I have fetched data with /players key
- I populate the cache /players/${id} for each fetched player using mutate()
- I move on the /players/1 detail page
- UX will first show the stale / cached data while it re-validates it in the background.

**Comment by frederikhors** [comment]
I don't know, But it's doable in this project, the problem is we need to swap the data for that key only when the promise is resolved, not before.

IMO.

**Comment by benbender** [comment]
IMHO: 
a) your sentences make no sense, are incomplete, plain false or simply not understandable.
b) no github-repo is your personal support-forum
c) "This is what I'm asking you!"? Are you nuts or simply rude? @ConsoleTVs provides a lib, developed in his freetime, free of charge, he even provides support and you dare to demand anything? Be grateful and nothing else. Period.
d) I'm out. I'll no longer answer questions or similar by you.

**Comment by frederikhors** [comment]
@benbender I love you. 😄

**Comment by benbender** [comment]
My verdict has fallen: you are plainly arrogant. For no obvious reason. #kthxbye #block

**Comment by frederikhors** [comment]
I really don't understand your behavior, @benbender.

Did you block me simply because I told you I love you? To avoid replying and wasting your time reading a reply to a useless message you wrote.

A message that doesn't make sense: I wasn't "demanding" anything from @ConsoleTVs; and among other things, as you well know and as @ConsoleTVs can tell, I am helping and collaborating with various PR on this splendid project.

You did not understand my question and you get angry, it seems like childish behavior to me.

Grow, live and let live.

Lots of little kisses.
