### ISSUE TITLE
Support synchronous `fetcher` function

### ISSUE THREAD

**Issue by rauchg** [ConsoleTVs/sswr#25]
For local storage cases like `localStorage`, I ran into an obscure error where it was complaining that the return value didn't have `.catch`. I fixed by turning my sync fetcher into an `async` function.

Furthermore, it might be worth considering accepting the fetcher as the second param, since that's how SWR also works.

**Comment by rauchg** [comment]
(Great work on sswr btw! Enjoying it 🤗 )

**Comment by ConsoleTVs** [comment]
@rauchg I quickly checked the types for the fetcher function:

```
type SWRFetcher<D = any> = (...props: any[]) => Promise<D>;
```

I'm curious how it allowed you to use a fetcher function that didn't return a Promise. I will cover this use case, but may I know if you were using Typescript and/or vscode?

**Comment by ConsoleTVs** [comment]
Fixed here: https://github.com/ConsoleTVs/swrev/commit/815d5ee5a94ce2cee2d0a13a5de61caf96eea22c
