### ISSUE TITLE
revalidateOnMount missing?

### ISSUE THREAD

**Issue by khromov** [ConsoleTVs/sswr#30]
👋 I saw a reference to the `revalidateOnMount` configuration option in [the README](https://github.com/ConsoleTVs/sswr#parameters) but I can't seem to find it in the code. Is it a feature that is planned for a future release?

It would be useful for me to set `revalidateOnMount: false` since I will be setting `initialData` from SvelteKit through SSR and don't want it to immediately refresh on the client.

**Comment by khromov** [comment]
I see that the function has been renamed to `revalidateOnStart`, see [separate PR](https://github.com/ConsoleTVs/sswr/pull/31) for small README fix.

**Comment by ConsoleTVs** [comment]
Thank you, you are correct
