### ISSUE TITLE
SvelteKit - Named export 'SWR' not found

### ISSUE THREAD

**Issue by mikenikles** [ConsoleTVs/sswr#37]
I use `sswr` in a SvelteKit application (`"@sveltejs/kit": "^1.0.0-next.442"`).

In dev, everything works fine. However, when I run `npm run build` and `npm run preview` and load a page that imports `sswr`, I see the following error:

```
SyntaxError: Named export 'SWR' not found. The requested module 'swrev' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'swrev';
const { SWR } = pkg;
```

Does anyone have a working example of `sswr` with SvelteKit? Maybe @khromov because of #34 🤔?

**Comment by ConsoleTVs** [comment]
Ah yeah, because vite 3 outputs and expects .mhs modules instead of .esm.js. I noticed that too. The fix is update this lib to vite 3 and change the pkg exports. Will do.

**Comment by arunrdd** [comment]
[Vite CommonJS Plugin](https://github.com/originjs/vite-plugins/tree/main/packages/vite-plugin-commonjs) might get this working.

**Comment by ConsoleTVs** [comment]
Fixed
