### ISSUE TITLE
Svelte 4 support

### ISSUE THREAD

**Issue by MaxLeiter** [ConsoleTVs/sswr#45]
This library has a version of Svelte 3 pinned in the package.json although [Svelte 4](https://svelte.dev/blog/svelte-4) support should be straightforward. I can open a PR if this would be accepted

ref: https://github.com/vercel-labs/ai/issues/271

**Comment by ConsoleTVs** [comment]
Please do

**Comment by ConsoleTVs** [comment]
Should be available with svelte 4 support at version: 1.11.0
