### ISSUE TITLE
SvelteKit - Function called outside component initialization

### ISSUE THREAD

**Issue by inzanez** [ConsoleTVs/sswr#7]
Hi

I'm trying to use sswr with a newly created SvelteKit project, building with the `node` adapter.
I have added some simple test after having had issues:
```
	import { useSWR } from 'sswr';

	try {
		const { data } = useSWR('http://jsonplaceholder.typicode.com/posts/1');
	} catch(e) {
		console.log(e);
	}
```
test to a
* route
* component

and I always get back the same error:

```
Error: Function called outside component initialization
    at get_current_component (index.mjs:813)
    at onMount (index.mjs:820)
    at l.useSvelte (index.js:1)
    at useSWR (index.js:1)
    at instance ([dialogId].svelte:42)
    at init (index.mjs?v=99bae134:1660)
    at new U5BdialogIdu5D ([dialogId].svelte:153)
    at createComponent (svelte-hooks.js:136)
    at U5BdialogIdu5D.targetCmp.$replace (svelte-hooks.js:183)
    at refreshComponent (proxy.js:170)
```

Any idea why that might be?

**Comment by ConsoleTVs** [comment]
What is this node adapter?

**Comment by inzanez** [comment]
Basically a build adapter that will result in an application build for NodeJs instead of a static file build.

**Comment by inzanez** [comment]
Ok, looking a bit more into this, it does seem that this doesn't work with SvelteKit yet. Any idea why that might be? I just started a new project using

```
npm init svelte@next my-app
cd my-app
npm install
npm run dev
```

and tried to run the sample code, resulting in the same error described above.

**Comment by frederikhors** [comment]
Same here with SvelteKit.

I'm not using node adapter.

So, the adapter is not the problem here.

I think we should initialize sswr before using it and use it with `setContext`/`getContext`.

**Comment by frederikhors** [comment]
Using the steps in https://kit.svelte.dev/docs#introduction-getting-started

you can try yourself: it doesn't work.

**Comment by ConsoleTVs** [comment]
Strange, last time I checked it worked... I'll check

**Comment by ConsoleTVs** [comment]
I just tried and it does work... 😕

**Comment by frederikhors** [comment]
Can you please create an `example` directory with the new Svelte Kit Demo project and sswr?

**Comment by ConsoleTVs** [comment]
Wait, I just double checked by installing the remote pkg and you're right it fails. I'm going to see what's going on here... Thanks for the error report, seems it worked fine with my local pkg :D

**Comment by ConsoleTVs** [comment]
@frederikhors How do you use onMount on a SSR svelte app??

```svelte
<script lang="ts">
    import {onMount} from 'svelte'
    onMount(() => {
        console.log('Hello World!')
    })
</script>

<div>Hello!</div>
```

This code throws the same error. How can I trigger this correctly?

**Comment by ConsoleTVs** [comment]
Are you sure this is not a problem with sveltekit rather than this lib? From https://svelte.dev/tutorial/onmount

I see: 

```
It's recommended to put the fetch in onMount rather than at the top level of the <script> because of server-side rendering (SSR). With the exception of onDestroy, lifecycle functions don't run during SSR, which means we can avoid fetching data that should be loaded lazily once the component has been mounted in the DOM.
```

**Comment by frederikhors** [comment]
Do you have any news on this, @ConsoleTVs?

**Comment by frederikhors** [comment]
Do you have any news on this, @ConsoleTVs?

**Comment by ConsoleTVs** [comment]
I tries to fix it and i was unable to. I got to the conclusion thst it might either be a bundle issue or something related. I am not an expert but sveltekit api is not yet stable either and it is due change, ao i might either wait for some PR from people who know more about the internals, wait for sveltekit to be stable or in short, have some more free time to allocate to this

**Comment by benbender** [comment]
It's not a but in this package, but in `sveltekit`. I saw the same problem on my own tinkering with `react-query` - so I opened a bug in `sveltekit. See https://github.com/sveltejs/kit/issues/2147.

**Comment by ConsoleTVs** [comment]
> It's not a bug in this package, but in `sveltekit`. I saw the same problem on my own tinkering with `react-query` - so I opened a bug in `sveltekit`. See https://github.com/sveltejs/kit/issues/2147.
> 
> 
> 
> Btw, it only happens when both preconditions are true: a) lifecycle-method called inside an installed package. b) in dev-mode. 
> 
> 
> 
> It works in svelte-repl though. So its likely a problem with the vite-dev-server.
> 
> 
> 
> PS: You can circumvent the bug for now by installing `swrev` and copy sswr to your local $lib-folder and import it from there.

That could explain why my local symlinked pkg was working lol

**Comment by frederikhors** [comment]
I think this fix it (for now): https://github.com/ConsoleTVs/sswr/pull/11.

Can we close this?

**Comment by ConsoleTVs** [comment]
Yes, I hope this will be fixed in the future by svelte plugin authors. Great work!
