### ISSUE TITLE
What's the status?

### ISSUE THREAD

**Issue by frederikhors** [ConsoleTVs/sswr#8]
Thanks for your work on this project.

Is it currently production-ready?

Is there any serious intention to maintain it in the future?

**Comment by ConsoleTVs** [comment]
Hello,

First of all thanks for the kind works. This package is just around 50 LOC of specific svelte code that can be seen at https://github.com/ConsoleTVs/sswr/blob/master/src/index.ts.

The rest is basically the underlying package located at https://github.com/ConsoleTVs/swrev.

I have used the vue version that also uses the same underlying package (https://github.com/ConsoleTVs/vswr) in a few production sites that I've build at work.

As with any other of my open source package, I can't guarantee any sort of stability outside of what my free time and willingness of the moment can grant me. This work is open source and under a very permissive license (MIT). If you ever feel the need to keep maintaining it, you're also free to do. I would also be able to accept other maintainers if that may interest you. I can also tell you that I don't use svelte that often, perhaps in some side projects but not that much althought I doubt those 50 LOC and my low svelte expertise can be of a problem. Perhaps, where I would need some help from svelte users is the SSR support or some sveltekit issue fixings that has been reported.

However, I regularly use vue at work, and when I do, I use the same underlying package, so in short, I am interested in keeping the project up to date due my own need.

Again, sorry if this is not the answer you're looking for, but it's hard to maintain a large number of open source packages, be at work every day and yet have some social life or in short, free time outside "code".

Let me know if you have some other concerns, thanks!
